language: generic
sudo: true
cache: apt
addons:
  apt:
    sources:
      - sourceline: ppa:hvr/z3
    packages:
      - z3

install:
  - curl https://leanprover.github.io/lean-nightly/build/lean-nightly-linux.tar.gz | tar xz -C ..
  - export PATH=../lean-nightly-linux/bin:$PATH

script:
  - leanpkg test
